### ISSUE TITLE
Incorrect payload sent to looking-glass when YAML syntax is wrong

### ISSUE THREAD

**Issue by hectorsector** [githubtraining/lab-scheduled-events#12]
When a user uses improper workflow syntax: 

<img width="646" alt="Screen Shot 2021-05-06 at 10 52 30 AM" src="https://user-images.githubusercontent.com/16547949/117319301-28841800-ae59-11eb-80e4-0c5a0ef3c61a.png">

We don't send the right `error.expected` and `error.got` fields to Looking Glass. In response, Looking Glass threw out:

```shell
grade-learnerOops, looks like something isn't working right. This is most likely not your fault! Please open an issue in this lab's template repository!
--
grade-learnerValueError: error.expected and error.got cannot be blank if msg is 'Error'
```
Additionally, could we write some tests so that the author can't get themselves into this problem for this (and future) labs? 

/cc @mattdavis0351

**Comment by hectorsector** [comment]
> This screenshot seems to be for scheduled events and this repo is for enable pages 😂😂

my bad, fixed now 

![](https://media.giphy.com/media/yvBAuESRTsETqNFlEl/giphy.gif)

**Comment by mattdavis0351** [comment]
@hectorsector The more I think about this, them more I'm wondering "who" has the responsibility here.

IF it's an Actions failure, like an invalid workflow rather than an invalid answer, then we should just prevent the Looking Glass step from running.  

I'd even be willing to be the grading action didn't run either. 

Can you send me a link to the workflow run please?

**Comment by mattdavis0351** [comment]
I used the workflow run that was linked in slack, which threw the same error as you posted.  The payload that was sent to Looking Glass is as follows:

```javascript
{
  "reports": [
    {
      "filename": "/home/runner/work/supreme-engine/supreme-engine/.github/workflows/stale-weekly.yml",
      "isCorrect": false,
      "display_type": "actions",
      "level": "fatal",
      "msg": "",
      "error": {
        "expected": "",
        "got": "An internal error occurred.  Please open an issue at: https://github.com/githubtraining/lab-scheduled-events and let us know!  Thank you"
      }
    }
  ]
}
```

So looking at this I'm starting to think Looking glass failed to handle it properly.  It apparently didn't like the blank `expected` field even though it should have converted the blank value into `null`.  

I'll examine LG to see if I can find the probelm.

**Comment by mattdavis0351** [comment]
all of this is being addressed [in this pull](https://github.com/githubtraining/looking-glass-action/pull/29)
